version: '3'

services:
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana
    container_name: kibana
    hostname: ${KIBANA_HOSTNAME:-kibana}
    domainname: ${DOMAIN:-domain.local}
    restart: always
    ports:
      - ${KIBANA_INTERFACE:-0.0.0.0}:${KIBANA_PORT:-5601}:5601
    environment:
      - ELASTICSEARCH_URL=https://${ELASTIC_HOSTNAME:-elastic}.${DOMAIN:-domain.local}:9200
      # - ELASTICSEARCH_URL=https://${ELASTIC_HOSTNAME:-elastic}:9200
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=admin
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERT=/opt/kibana/config/cert/certificate.crt.pem
      - SERVER_SSL_CERTIFICATE
      - SERVER_SSL_KEY=/opt/kibana/config/cert/private.key.pem
    volumes:
      - ./kibana/kibana.yml:/opt/kibana/config/kibana.yml:ro

      - ${KIBANA_CERT_SOURCE:-./cert/kibana/}:/opt/kibana/config/cert/:ro
    depends_on:
      - elastic
    links:
      - elastic:elastic
      # - wazuh:wazuh