version: '3.8'

services:
  suricata:
    image: jasonish/suricata
    container_name: suricata
    restart: unless-stopped
    hostname: ${SURICATA_HOSTNAME:-suricata}
    network_mode: host
    cap_add:
      - net_admin
      - sys_nice
    volumes:
      - suricata_log_data:/var/log/suricata
      # - /var/lib/suricata
      # - /etc/suricata
    command: >

volumes:
  suricata_log_data: