version: '3.7'

# services:
#   postgres:
#     image: postgres
#     container_name: guacamole-postgres
#     restart: unless-stopped
#     hostname: guacamole-postgres
#     volumes:
#       - guacamole-postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: ${POSTGRES_GUACAMOLE_DB:-guacamole}
#       POSTGRES_USER: ${POSTGRES_GUACAMOLE_DB_USER:-guacamole}
#       POSTGRES_PASSWORD: ${POSTGRES_GUACAMOLE_DB_PASSWD:-guacamole}

#   guacd:
#     image: guacamole/guacd
#     container_name: guacamole-guacd
#     restart: unless-stopped
#     hostname: guacamole-guacd
    


#   guacamole:
#     image: guacamole/guacamole
#     container_name: guacamole_compose
#     restart: unless-stopped
#     hostname: ${GUACAMOLE_HOSTNAME:-guacamol}.${DOMAIN:-domain.local}
#     environment:
#       GUACD_HOSTNAME: guacamole-guacd
#       POSTGRES_HOSTNAME: guacamole-postgres
#       POSTGRES_DATABASE: ${POSTGRES_GUACAMOLE_DB:-guacamole}
#       POSTGRES_PASSWORD: ${POSTGRES_GUACAMOLE_DB_PASSWD:-guacamole}
#       POSTGRES_USER: ${POSTGRES_GUACAMOLE_DB_USER:-guacamole}
#     depends_on:
#       - guacd
#       - postgres
#     ports:
#       - ${GUACAMOLE_INTERFACE:-0.0.0.0}:${GUACAMOLE_PORT:-8080}:8080/tcp

# volumes:
#   guacamole-postgres_data:

services:
  init-guacamole-db:
      image: guacamole/guacamole:latest
      command: ["/bin/sh", "-c", "test -e /init/initdb.sql && echo 'init file already exists' || /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql" ]
      volumes:
        - dbinit:/init    

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - dbinit:/docker-entrypoint-initdb.d        
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-guacdb}
      POSTGRES_PASSWORD: pass
    depends_on:
      - init-guacamole-db

  guacd:
    image: guacamole/guacd:latest
    restart: unless-stopped

  guac:
    image: guacamole/guacamole:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: ${POSTGRES_USER:-guacdb}
      POSTGRES_USER: ${POSTGRES_USER:-guacdb}
      POSTGRES_PASSWORD: pass
    depends_on:
      - postgres
      - guacd

volumes:
  dbinit:
    driver: local
  dbdata:
    driver: local