version: '3'

services:
  keycloak:
    entrypoint:
      - bash
      - -c 
      - |
          i=10
          until (echo > /dev/tcp/${IPA_HOSTNAME:-ipa.domain.lol}/443 && echo > /dev/tcp/${IPA_HOSTNAME:-ipa.domain.lol}/636 && echo > /dev/tcp/${IPA_HOSTNAME:-ipa.domain.lol}/464 && echo > /dev/tcp/${IPA_HOSTNAME:-ipa.domain.lol}/53) >/dev/null 2>&1 ; do
            echo "IPA is unavailable - sleeping $$i secondes"
            sleep $$i;
            #((i++))
          done
          /opt/jboss/tools/docker-entrypoint.sh
