version: '3'

services:
  postgres:
    image: postgres
    container_name: keycloak-postgres
    restart: unless-stopped
    hostname: keycloak-postgres
    volumes:
      - keycloak-postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_DB_PASSWORD:-keycloak}
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    hostname: ${KEYCLOAK_HOSTNAME:-keycloak}
    domainname: ${DOMAIN:-domain.local}
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: ${KEYCLOAK_POSTGRES_DB:-keycloak}
      DB_USER: ${KEYCLOAK_POSTGRES_DB_USER:-keycloak}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_POSTGRES_DB_PASSWORD:-keycloak}
    # command:
    #   - -b
    #   - ${KEYCLOAK_INTERFACE:-0.0.0.0}
    depends_on:
      - postgres

volumes:
  keycloak-postgres_data:
