version: "3"
services:

  wiki-db:
    container_name: wiki-db
    hostname: wiki-db
    image: docker.io/postgres:11-alpine
    environment:
      POSTGRES_DB: ${WIKI_DB:-wiki}
      POSTGRES_USER: ${WIKI_DB_USER:-wiki}
      POSTGRES_PASSWORD: ${WIKI_DB_PASSWORD:-wiki}
      # POSTGRES_HOST_AUTH_METHOD: trust
    # logging:
    #   driver: "none"
    restart: always
    # volumes:
    #   - db-data:/var/lib/postgresql/data

  wiki:
    container_name: wiki
    hostname: wiki
    image: docker.io/requarks/wiki
    depends_on:
      - wiki-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki-db
      DB_PORT: 5432
      DB_NAME: ${WIKI_DB:-wiki}
      DB_USER: ${WIKI_DB_USER:-wiki}
      DB_PASS: ${WIKI_DB_PASSWORD:-wiki}
    restart: always
    ports:
      - "8080:3000"

# volumes:
#   db-data: