version: '3'

services:
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${IPA_HOSTNAME:-ipa}.${IPA_DOMAIN:-domain.local}
    ports:
      - 4443:443
    depends_on:
      - ipa