version: '3'

services:
  ipa:
    image: freeipa/freeipa-server:centos-8
    container_name: ipa
    restart: unless-stopped
    hostname: ${IPA_HOSTNAME:-ipa}.${IPA_DOMAIN:-domain.local}
    # domainname: ${IPA_DOMAIN:-domain.local}
    # environment:
    #   IPA_SERVER_HOSTNAME: ${IPA_HOSTNAME:-ipa.domain.local} # Optionnal
    # tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ipa_data:/data
    sysctls:
      - net.ipv6.conf.lo.disable_ipv6=0
    # privileged: true # Required if command option --hostname
    command: >
      --domain=${IPA_DOMAIN:-domain.local}
      --realm=${IPA_REALM:-DOMAIN.LOL}
      --http-pin=${IPA_HTTP_PIN:-V@grant1}
      --dirsrv-pin=${IPA_DIRSRV_PIN:-V@grant1}
      --ds-password=${IPA_DS_PASSWORD:-V@grant1}
      --admin-password=${IPA_ADMIN_PASSWORD:-V@grant1}
      --unattended
      ${IPA_START_OPTION:---setup-dns}
    # # - --ip-address=${IPA_INTERFACE:-0.0.0.0} # not working with 0.0.0.0
    # # - --hostname=${IPA_HOSTNAME:-ipa.domain.local} # Required privileged option
    # # - --no-host-dns
    # - --no-dnssec-validation
    # # - --setup-dns
    # - --auto-forwarders
    # # - --allow-zone-overlap
    # - --no-ntp  # Will not start ntp
    # # - --ntp-pool=fr.pool.ntp.org
    # # - --unattended
    # - ${IPA_START_OPTION}
    ports:
      # FreeIPA WebUI
      - ${IPA_INTERFACE:-0.0.0.0}:80:80
      - ${IPA_INTERFACE:-0.0.0.0}:443:443
      # Kerberos
      - ${IPA_INTERFACE:-0.0.0.0}:88:88
      - ${IPA_INTERFACE:-0.0.0.0}:88:88/udp
      - ${IPA_INTERFACE:-0.0.0.0}:464:464
      - ${IPA_INTERFACE:-0.0.0.0}:464:464/udp
      # LDAP
      - ${IPA_INTERFACE:-0.0.0.0}:389:389
      - ${IPA_INTERFACE:-0.0.0.0}:636:636
      # DNS
      - ${IPA_INTERFACE:-0.0.0.0}:53:53
      - ${IPA_INTERFACE:-0.0.0.0}:53:53/udp
      # NTP
      - ${IPA_INTERFACE:-0.0.0.0}:123:123
      - ${IPA_INTERFACE:-0.0.0.0}:123:123/udp
      # Other
      - ${IPA_INTERFACE:-0.0.0.0}:7389:7389
      - ${IPA_INTERFACE:-0.0.0.0}:9443:9443
      - ${IPA_INTERFACE:-0.0.0.0}:9444:9444
      - ${IPA_INTERFACE:-0.0.0.0}:9445:9445
    # healthcheck:
    #   test: ipa 2>/dev/null; if [ $$? -ne 2 ]; then exit 1; fi
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s

volumes:
  ipa_data:
