version: '3'

services:
  ipa:
    image: freeipa/freeipa-server:centos-8
    container_name: ipa
    restart: unless-stopped
    hostname: ${IPA_HOSTNAME:-ipa}
    #.${IPA_DOMAIN:-domain.local}
    domainname: ${IPA_DOMAIN:-domain.local}
    environment:
      TZ: ${TIME_ZONE:-Europe/Paris}
      IPA_SERVER_IP: ${IPA_INTERFACE:-0.0.0.0}
      IPA_SERVER_HOSTNAME: ${IPA_HOSTNAME:-ipa}.${IPA_DOMAIN:-domain.local}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ipa_data:/data
    sysctls:
      - net.ipv6.conf.lo.disable_ipv6=0
    # privileged: true # Required if command option --hostname=${IPA_HOSTNAME:-ipa}.${IPA_DOMAIN:-domain.local}
    command: >
      --domain="${IPA_DOMAIN:-domain.local}"
      --realm="${IPA_REALM:-DOMAIN.LOL}"

      --ds-password="${IPA_DS_PASSWORD:-V@grant1}"
      --admin-password="${IPA_ADMIN_PASSWORD:-V@grant1}"      

      --http-pin="${IPA_HTTP_PIN}"
      --dirsrv-pin="${IPA_DIRSRV_PIN}"
      --pkinit-pin="${IPA_KERBEROS_PIN}"

      --unattended
      
      ${IPA_START_OPTION:---setup-dns --forwarder=1.0.0.1 --forwarder=1.1.1.1 --auto-forwarders --ntp-pool=pool.ntp.org}
    # --hostname=${IPA_HOSTNAME:-ipa}.${IPA_DOMAIN:-domain.local} # Required privileged: true option
    ports:
      # FreeIPA WebUI
      - ${IPA_INTERFACE:-0.0.0.0}:${IPA_HTTP_PORT:-80}:80
      - ${IPA_INTERFACE:-0.0.0.0}:${IPA_HTTPS_PORT:-443}:443
      # Kerberos
      - ${IPA_INTERFACE:-0.0.0.0}:88:88
      - ${IPA_INTERFACE:-0.0.0.0}:88:88/udp
      - ${IPA_INTERFACE:-0.0.0.0}:464:464
      - ${IPA_INTERFACE:-0.0.0.0}:464:464/udp
      # LDAP
      - ${IPA_INTERFACE:-0.0.0.0}:389:389
      - ${IPA_INTERFACE:-0.0.0.0}:636:636

volumes:
  ipa_data:
